### PR TITLE
Minor rendering optimizations

### PR DESCRIPTION
**Pull request by Hixie**
Turns out the `Path()` constructor was taking half the time of rendering an image. Using a static Path removes all of that time.

The other optimizations are less significant. `Path.close()` is expensive, but is pointless since we always fill (this may not be a real savings, since the work presumably is just done when painting now, but it does get it off the profile). The `nextByte` getter is very hot; inlining `nextByte` seemed to help, but I might be imagining it. The real problem here is that what we really want to do is just walk a buffer with a pointer but Dart doesn't give us that option short of playing with dart:ffi and that seems unnecessarily complicated...

Tests still pass (tested locally).

### CODE REVIEW

**Comment by Hixie** [comment]
cc @dnfield

**Review by dnfield — APPROVED** [review]
Lgtm

**Comment by Hixie** [comment]
@nigeltao This is ready to land. :-)

**Comment by nigeltao** [comment]
> Using a static Path removes all of that time.

Does static-ness mean that you can no longer decode multiple IconVG files concurrently? (This may just be a Dart newbie question on my behalf. IIUC Dart is single threaded but Futures still let you overlap work somehow).

Even if "no more concurrent decoding" is true, we can fix that later, especially if `Path()` constructors get faster. I'll merge.

**Comment by Hixie** [comment]
This code is single-threaded and uninterruptible so it's not possible for the `Path` object to be used by two decodes simultaneously.

**Pull request merged**
